spring:
  application:
    name: product-service
  data:
    mongodb:
        uri: mongodb://localhost:27017/product-service
        # authentication-database: adming
        # username: rootuser
        # password: rootuser
# logging:
#   level:
#     org:
#         springframework:
#             data:
#                 mongodb:
#                     core:
#                         MongoTemplate: debug

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
