spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=order-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/

management:
  health:
    circuitbreakers:
      enabled:  true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# resilience properties
resilience4j:
  circuitbreaker:
    instances:
      order-service:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3 
        automatic-transition-from-open-to-half-open-enabled: true


