spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=inventory-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/